# Generated by Django 5.1.3 on 2024-11-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('anio_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id_monografia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_defensa', models.DateField()),
                ('nota_defensa', models.FloatField()),
                ('tiempo_otorgado', models.IntegerField()),
                ('tiempo_defensa', models.IntegerField()),
                ('tpr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('carnet', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('anio_nacimiento', models.DateField()),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonoEstudiantes.monografia')),
            ],
        ),
        migrations.CreateModel(
            name='ProfMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonoEstudiantes.docente')),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonoEstudiantes.monografia')),
            ],
            options={
                'unique_together': {('monografia', 'docente')},
            },
        ),
    ]
